version: '3.13.1'
services:
  my-mongo-db:
    container_name: my-mongo-db
    image: mongo:5.0
    ports:
      - '27018:27017'
    volumes:
      - type: bind
        source: ./mongo-data
        target: /data/db
